import {useState} from 'react';
import {Link} from 'react-router-dom';
import {StoreLayout} from '../layouts/StoreLayout';
import {BackofficeLayout} from '../layouts/BackofficeLayout';
import {useResource} from '../services/useResource';
import {post} from '../services/http';
const labels:Record<string,string>={OrderCreated:'Pedido criado',OrderCancelled:'Pedido cancelado',PaymentPaid:'Pagamento confirmado',PaymentPaidReview:'Pagamento requer análise',PaymentReview:'Pagamento em análise',PaymentRefunded:'Estorno confirmado',FulfillmentProcessing:'Pedido em processamento',FulfillmentPicking:'Pedido em separação',FulfillmentPacked:'Pedido embalado',FulfillmentPartiallyShipped:'Pedido enviado parcialmente',FulfillmentShipped:'Pedido enviado',FulfillmentDelivered:'Pedido entregue'};
export function NotificationsPage({admin=false}:{admin?:boolean}){
 const [page,setPage]=useState(1);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const base=admin?'/v1/notifications':'/v1/store/notifications';const result=useResource<{id:string;orderId:number;kind:string;state?:string;attempts?:number;lastError?:string;readAt?:string}[]>(base+'?page='+page,revision);const Layout=admin?BackofficeLayout:StoreLayout;
 return <Layout><main className="commerce-admin"><h1>{admin?'Fila de notificações do portal':'Minhas notificações'}</h1><p>Atualizações disponíveis neste portal. Envio por e-mail ainda não configurado.</p>{(error||result.error)&&<p role="alert">{error||result.error}</p>}<button onClick={()=>setRevision(v=>v+1)}>Atualizar</button>{result.data?.map(n=><section className="form-card" key={n.id}><h2>{labels[n.kind]||n.kind}</h2><Link to={admin?'/admin/orders':'/orders/'+n.orderId}>Pedido #{n.orderId}</Link>{admin?<p>{n.state==='Processed'?'Disponibilizada no portal':n.state==='Failed'?'Falha: requer análise':'Aguardando processamento'} · Tentativas: {n.attempts}</p>:<p>{n.readAt?'Lida':'Não lida'}</p>}{n.lastError&&<p>{n.lastError}</p>}{(admin?n.state==='Failed':!n.readAt)&&<button disabled={busy} onClick={()=>{setBusy(true);void post(base+'/'+n.id+(admin?'/retry':'/read')).then(()=>setRevision(v=>v+1)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{admin?'Reprocessar':'Marcar como lida'}</button>}</section>)}{!result.loading&&!result.data?.length&&<p>Nenhuma notificação nesta página.</p>}<nav className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button disabled={(result.data?.length||0)<20} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav></main></Layout>;
}
