using CloudShopping.Domain.Primitives.Results;
using CloudShopping.Application.Abstractions.Data;
using CloudShopping.Application.Abstractions.Services;
using CloudShopping.Application.Features.Storefront.Contracts;
using CloudShopping.Domain.Entities.Customers;
using CloudShopping.Domain.Enums;
using MediatR;
using System.Text.Json;
namespace CloudShopping.Application.Features.Storefront.Queries.GetStoreShipping;
public sealed record GetStoreShippingQuery(int CustomerId, int AddressId) : IRequest<Result<IReadOnlyList<StoreShippingView>>>;
