using CloudShopping.Domain.Primitives.Results;
using CloudShopping.Application.Abstractions.Data;
using CloudShopping.Application.Abstractions.Services;
using CloudShopping.Application.Features.Storefront.Contracts;
using CloudShopping.Domain.Entities.Customers;
using CloudShopping.Domain.Enums;
using MediatR;
using System.Text.Json;
namespace CloudShopping.Application.Features.Storefront.Commands.AddStoreAddress;
public sealed record AddStoreAddressCommand(int CustomerId, string Street, string Number, string? Neighborhood, string City, string State, string ZipCode) : IRequest<Result<int>>;
