<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<!-- Necessário para IHttpContextAccessor, AddHttpContextAccessor, IWebHostEnvironment sem depender do SDK Web -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="SixLabors.ImageSharp" Version="4.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CloudShopping.Application\CloudShopping.Application.csproj" />
		<ProjectReference Include="..\CloudShopping.Domain\CloudShopping.Domain.csproj" />
	</ItemGroup>
</Project>
