import {useState} from 'react';
import {BackofficeLayout} from '../../layouts/BackofficeLayout';
import {useResource} from '../../services/useResource';
import {request} from '../../services/http';
type Details={id:number;name:string;sku:string;version:number;slug:string;description:string;brand:string|null;weightKg:number;widthCm:number;heightCm:number;lengthCm:number;familyCode:string|null;variantLabel:string|null;attributesJson:string};
export function CatalogDetailsPage(){
 const [page,setPage]=useState(1);const [revision,setRevision]=useState(0);const [selected,setSelected]=useState<Details>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const result=useResource<Details[]>('/v1/catalog-details?page='+page,revision);
 return <BackofficeLayout><main className="commerce-admin"><h1>Ficha comercial e variantes</h1><p>Cadastre cada SKU em Produtos e agrupe variantes pelo mesmo código de família. Preço e estoque permanecem independentes. Peso e dimensões zero indicam ficha de transporte ainda incompleta.</p>{(error||result.error)&&<p role="alert">{error||result.error}</p>}
 {result.data?.map(p=><button key={p.id} className="form-card" onClick={()=>setSelected(p)}>{p.name} · {p.sku}</button>)}<nav className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button disabled={(result.data?.length||0)<20} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav>
 {selected&&<form key={selected.id+':'+selected.version} className="form-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');let attributes:Record<string,string>;try{const rows=String(f.get('attributes')).split('\n').filter(x=>x.trim());const entries=rows.map(row=>{const colon=row.indexOf(':');if(colon<1)throw new Error();return [row.slice(0,colon).trim(),row.slice(colon+1).trim()];});attributes=Object.fromEntries(entries);}catch{setError('Use um atributo por linha: nome: valor.');setBusy(false);return;}void request('/v1/catalog-details/'+selected.id,{method:'PUT',body:JSON.stringify({version:selected.version,slug:f.get('slug'),description:f.get('description'),brand:f.get('brand'),weightKg:Number(f.get('weightKg')),widthCm:Number(f.get('widthCm')),heightCm:Number(f.get('heightCm')),lengthCm:Number(f.get('lengthCm')),familyCode:f.get('familyCode'),variantLabel:f.get('variantLabel'),attributes})}).then(()=>{setSelected(undefined);setRevision(v=>v+1);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>
 <h2>{selected.name}</h2><label>URL do produto<input name="slug" required maxLength={150} pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={selected.slug}/></label><label>Descrição<textarea name="description" maxLength={10000} defaultValue={selected.description}/></label><label>Marca<input name="brand" maxLength={100} defaultValue={selected.brand||''}/></label>
 {(['weightKg','widthCm','heightCm','lengthCm'] as const).map((field,i)=><label key={field}>{['Peso (kg)','Largura (cm)','Altura (cm)','Comprimento (cm)'][i]}<input name={field} required type="number" min="0" max="10000" step={i===0?'0.001':'0.01'} defaultValue={selected[field]}/></label>)}
 <label>Código da família (opcional)<input name="familyCode" maxLength={50} defaultValue={selected.familyCode||''}/></label><label>Identificação da variante (ex.: Azul / G)<input name="variantLabel" maxLength={100} defaultValue={selected.variantLabel||''}/></label><label>Atributos (um por linha, ex.: Cor: Azul)<textarea name="attributes" defaultValue={Object.entries(JSON.parse(selected.attributesJson) as Record<string,string>).map(([name,value])=>name+': '+value).join('\n')}/></label><button disabled={busy}>Salvar ficha</button><button type="button" disabled={busy} onClick={()=>setSelected(undefined)}>Cancelar</button></form>}
 </main></BackofficeLayout>;
}
