import {useState} from 'react';
import {BackofficeLayout} from '../../layouts/BackofficeLayout';
import {useResource} from '../../services/useResource';
import {post,request} from '../../services/http';
import {money} from '../../services/storeService';
export function CouponsPage(){
 const [revision,setRevision]=useState(0);const [page,setPage]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const result=useResource<{id:string;code:string;kind:string;value:number;usedCount:number;usageLimit:number;enabled:boolean;version:number}[]>('/v1/coupons?page='+page,revision);
 return <BackofficeLayout><main className="commerce-admin"><h1>Cupons</h1><p>Um cupom por pedido. Desconto sobre os produtos; frete não recebe desconto. Cancelamento antes do pagamento libera o uso; estorno não libera automaticamente.</p>{(error||result.error)&&<p role="alert">{error||result.error}</p>}
 <form className="form-card" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setError('');void post('/v1/coupons',{code:f.get('code'),kind:f.get('kind'),value:Number(f.get('value')),minimumSubtotal:Number(f.get('minimumSubtotal')),usageLimit:Number(f.get('usageLimit')),perCustomerLimit:Number(f.get('perCustomerLimit')),startsAt:new Date(String(f.get('startsAt'))).toISOString(),endsAt:new Date(String(f.get('endsAt'))).toISOString()}).then(()=>{setRevision(v=>v+1);form.reset();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>
 <h2>Criar cupom</h2><label>Código<input name="code" required minLength={3} maxLength={40} pattern="[A-Za-z0-9_-]+"/></label><label>Tipo<select name="kind"><option value="Percent">Percentual</option><option value="Fixed">Valor fixo em reais</option></select></label><label>Desconto<input name="value" type="number" min="0.01" step="0.01" required/></label><label>Subtotal mínimo<input name="minimumSubtotal" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Limite total de usos<input name="usageLimit" type="number" min="1" max="1000000" required/></label><label>Usos por cliente<input name="perCustomerLimit" type="number" min="1" defaultValue="1" required/></label><label>Início (seu horário local)<input name="startsAt" type="datetime-local" required/></label><label>Fim (seu horário local)<input name="endsAt" type="datetime-local" required/></label><button disabled={busy}>Criar cupom</button></form>
 {result.data?.map(c=><section className="form-card" key={c.id}><h2>{c.code}</h2><p>{c.kind==='Percent'?c.value+'%':money(c.value)} · {c.usedCount}/{c.usageLimit} usos · {c.enabled?'Habilitado':'Pausado'}</p><button disabled={busy} onClick={()=>{setBusy(true);void request('/v1/coupons/'+c.id+'/enabled',{method:'PUT',body:JSON.stringify({version:c.version,enabled:!c.enabled})}).then(()=>setRevision(v=>v+1)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{c.enabled?'Pausar':'Habilitar'}</button></section>)}
 <nav className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button disabled={(result.data?.length||0)<20} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav></main></BackofficeLayout>;
}
