import {useState} from 'react';
import {Link} from 'react-router-dom';
import {BackofficeLayout} from '../../layouts/BackofficeLayout';
import {useResource} from '../../services/useResource';
import {request} from '../../services/http';
import {money} from '../../services/storeService';
import {label} from '../../services/operations';
type Summary={orderCount:number;orderedGross:number;approvedGross:number;refundedGross:number;pendingGross:number;updatedAt:string;states:{state:string;count:number}[];daily:{date:string;count:number;gross:number}[];lowStock:{id:number;name:string;physicalStock:number;reservedStock:number;available:number}[]};
export function Dashboard(){
 const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10));const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10));const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const query=`?from=${from}&to=${to}`;const result=useResource<Summary>(from&&to?'/v1/reports'+query:null);const d=result.data;
 return <BackofficeLayout><main className="commerce-admin"><h1>Indicadores da loja</h1><p>Pedidos criados no período, em UTC. Valores de pagamento são brutos e refletem o estado atual desses pedidos; não representam saldo liquidado nem incluem taxas do provedor.</p><div className="form-card"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy||!d} onClick={()=>{setBusy(true);void request<{fileName:string;content:string}>('/v1/reports/export'+query).then(x=>{const url=URL.createObjectURL(new Blob(['\ufeff',x.content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=x.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Exportar pedidos (CSV)</button></div>
 {(error||result.error)&&<p role="alert">{error||result.error}</p>}{result.loading?<p>Carregando indicadores…</p>:d&&<><div className="finance-list">{[['Pedidos',String(d.orderCount)],['Total bruto dos pedidos',money(d.orderedGross)],['Pagamentos aprovados brutos',money(d.approvedGross)],['Estornos integrais confirmados',money(d.refundedGross)],['Pedidos aguardando pagamento',money(d.pendingGross)]].map(([name,value])=><section className="form-card" key={name}><h2>{name}</h2><strong>{value}</strong></section>)}</div><p>Atualizado em {new Date(d.updatedAt.endsWith('Z')?d.updatedAt:d.updatedAt+'Z').toLocaleString('pt-BR')}</p><h2>Etapas de atendimento</h2>{d.states.map(s=><p key={s.state}>{label(s.state)}: {s.count}</p>)}<h2>Pedidos por dia (UTC)</h2><table><thead><tr><th>Data</th><th>Pedidos</th><th>Total bruto</th></tr></thead><tbody>{d.daily.map(day=><tr key={day.date}><td>{day.date.slice(0,10)}</td><td>{day.count}</td><td>{money(day.gross)}</td></tr>)}</tbody></table>{!d.daily.length&&<p>Nenhum pedido no período.</p>}<h2>Estoque disponível baixo (até 5 unidades)</h2>{d.lowStock.map(p=><p key={p.id}><Link to="/admin/products">{p.name}</Link> · Físico {p.physicalStock} · Reservado {p.reservedStock} · Disponível {p.available}</p>)}</>}
 </main></BackofficeLayout>;
}
