import {useState} from 'react';
import {BackofficeLayout} from '../../layouts/BackofficeLayout';
import {useResource} from '../../services/useResource';
import {post,request} from '../../services/http';
import {type PaymentAttempt,paymentLabels} from '../../services/payments';
import {money} from '../../services/storeService';
export function FinancePayments(){
    const [page,setPage]=useState(1);const [version,setVersion]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [refund,setRefund]=useState<PaymentAttempt>();
    const [recover,setRecover]=useState<PaymentAttempt>();const [paymentId,setPaymentId]=useState('');
    const [history,setHistory]=useState<{kind:string;requestedBy:string;requestedAt:string}[]>();
    const result=useResource<PaymentAttempt[]>('/v1/asaas/admin/payments?page='+page,version);
    const run=async(id:number,action:string)=>{setBusy(true);setMessage('');try{await post('/v1/asaas/admin/orders/'+id+'/'+action);setVersion(v=>v+1);setRefund(undefined);setMessage('Solicitação processada. Confira o estado conciliado da cobrança.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
    return <BackofficeLayout><main className="commerce-admin"><h1>Pagamentos e conciliação</h1><p>Operações reais na conta configurada para cada pedido. Em sandbox, os valores são de teste.</p>
        {(message||result.error)&&<p className="notice" role="status">{message||result.error}</p>}
        {recover&&<form className="form-card" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('/v1/asaas/admin/orders/'+recover.orderId+'/recover',{paymentId});setRecover(undefined);setPaymentId('');setVersion(v=>v+1);}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><h2>Recuperar cobrança do pedido #{recover.orderId}</h2><p>Informe o identificador encontrado no Asaas. Conta, cliente, valor e referência serão conferidos antes de vincular.</p><label>ID da cobrança<input required pattern="pay_[A-Za-z0-9_-]+" value={paymentId} onChange={e=>setPaymentId(e.target.value)}/></label><button disabled={busy}>Verificar e recuperar</button><button type="button" disabled={busy} onClick={()=>setRecover(undefined)}>Voltar</button></form>}
        {history&&<section className="form-card"><h2>Histórico de solicitações</h2>{history.length?history.map((h,i)=><p key={i}>{h.kind} · {h.requestedBy} · {new Date(h.requestedAt+'Z').toLocaleString('pt-BR')}</p>):<p>Nenhuma solicitação registrada.</p>}<button onClick={()=>setHistory(undefined)}>Fechar histórico</button></section>}
        {refund&&<section className="form-card" role="dialog" aria-label="Confirmar estorno"><h2>Estorno integral do pedido #{refund.orderId}</h2><p>Solicitar devolução de {money(refund.amount)} pelo Asaas. Esta ação não repõe estoque físico.</p><button disabled={busy} onClick={()=>void run(refund.orderId,'refund')}>Confirmar solicitação de estorno</button><button disabled={busy} onClick={()=>setRefund(undefined)}>Voltar</button></section>}
        {result.loading?<p>Carregando cobranças…</p>:!result.data?.length?<p>Nenhuma tentativa nesta página.</p>:<div className="finance-list">{result.data.map(a=><section className="form-card" key={a.id}><h2>Pedido #{a.orderId} · {money(a.amount)}</h2><p>{a.method} · {paymentLabels[a.state]||a.state} {a.providerStatus&&'· '+a.providerStatus}</p>{a.lastError&&<p className="notice error">{a.lastError}</p>}<div className="finance-actions"><button disabled={busy} onClick={()=>void request<{kind:string;requestedBy:string;requestedAt:string}[]>('/v1/asaas/admin/orders/'+a.orderId+'/operations').then(setHistory).catch(e=>setMessage(e.message))}>Histórico</button>{['Unknown','Review','Creating'].includes(a.state)&&<button disabled={busy} onClick={()=>setRecover(a)}>Recuperar cobrança</button>}<button disabled={busy} onClick={()=>void run(a.orderId,'refresh')}>Conciliar</button>{!['Paid','PaidReview','Refunded'].includes(a.state)&&<button disabled={busy} onClick={()=>void run(a.orderId,'cancel')}>Solicitar cancelamento</button>}{['Paid','PaidReview','Review'].includes(a.state)&&!a.refundRequested&&<button disabled={busy} onClick={()=>setRefund(a)}>Estornar integralmente</button>}</div></section>)}</div>}
        <nav className="pagination"><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button disabled={(result.data?.length||0)<20||busy} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav>
    </main></BackofficeLayout>;
}
